### ISSUE TITLE
Problems getting this to work

### ISSUE THREAD

**Issue by dgutov** [Mon-Ouie/ruby-dev.el#2]
1. If I don't set `ruby-dev-path` manually, it points to my $HOME, largely because it's where my `loaddefs.el` lives (and I have a custom autoloading mechanism). There's no reason to put `###autoload` above `(defvar ruby-dev-path ...)` and its neighbors: simple variable access doesn't trigger autoloading anyway.
2. Provided `ruby-dev-path` is correct, `ruby-dev-eval-region` works. But if I try `ruby-dev-show-doc`, it infloops somewhere, and starts slowing down Emacs a lot, even after `keyboard-quit`.

The only message it shows is this:

```
ruby-dev failed to parse line: /home/gutov/vc/ruby-dev.el/ruby-dev.rb:285: Use RbConfig instead of obsolete and deprecated Config.
```

If I try to run `ruby ruby-dev.rb` from a console, it just sits there. No output, no errors.

```
$ ruby --version
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
```

```
$ gem list
...
pry-doc (0.4.4)
pry-rails (0.1.6)
...
yard (0.8.3)
...
```

**Comment by Mon-Ouie** [comment]
Hey,

I removed the `###autoload` annotation before ruby-dev-path. Thanks for telling me about that. Should the defcustom forms also not have it?

I think your other problem is related to completion trying to retrieve way too many matching results for short inputs. I made a commit that limits the amount of results retrieved to a reasonable value (1000), which seems to run pretty quickly here). Does that solve your problem?

**Comment by dgutov** [comment]
Uh, sorry, if you goal was to allow the user to customize the package without loading it first, the autoloads do make sense. And without autoloading `ruby-dev-path`, `ruby-dev-script-path` defcustom form raises an error.

This doesn't work for me, though, so if you fine with limiting the user to `M-x customize-group RET ruby-dev RET` until the package is loaded, you can leave only the `###;;;autoload` above `defgroup` forms.

> Does that solve your problem?

Yep, `ruby-dev-show-doc` works now, although a) I expected it to use the symbol at point, and b) it skips a lot of classes this way, so it doesn't look like a real solution. If I type `String` or `Array`, it only shows the class methods on `Kernel`.

**Comment by Mon-Ouie** [comment]
Oh, right; I should have checked for that. I think omitting `autoload` before those `defcustom` forms is reasonable.

As for a), I guess it would be a nice feature, but I'm not sure how the symbol at point would be retrieved. Just taking the word (or similar) at point wouldn't be of much help, since it doesn't include the class.

I don't understand what you mean in b). When I type `Array<TAB>`, the completions include many methods specific to `Array`, e.g. `Array#last`.

**Comment by dgutov** [comment]
Huh. It was a problem with `ido-ubiquitous`, `ido-completing-read` seems to not support completion when the second argument is a function properly, the function is only called once. With `ido-ubiquitous` disabled, it indeed works properly. Thanks for the support!

A couple of other notes:
1) You might want to move `(ruby-dev-ensure)` call from `ruby-dev-show-doc` to `ruby-dev-doc-completions`. Otherwise, I have to call some other command first.
2) The completion mechanism requires me to know the class name first. IOW, I can't type `map` and then pick from the classes that have this method. If I'm reading some unfamiliar code, I probably don't know all the classes involved.

Full disclosure: I'm developing a [package with somewhat similar functionality](https://github.com/dgutov/robe). Just stumbled on this one a few days ago when reading `pry` wiki, and I'm mostly trying to look for ideas I can use and pieces that would be easy to extract. So far, doc pages for classes look really nice, but not particularly extractable.

**Comment by Mon-Ouie** [comment]
To be fair, it might be related to the fact that the completion proc does not provide all results immediately — since generating all symbols takes way too much time to be acceptable.

I think 2) could be a nice feature, but I'm not sure using it for autocompletion would work well. I'm thinking more of something like Pry's `find-method` command, generating the output to a new buffer from which you can jump to the found methods, etc.

Well, good luck with your project ;)

**Comment by dgutov** [comment]
> To be fair, it might be related to the fact that the completion proc does not provide all results immediately

Sure, it is. But when there is a non-empty input, `completing-read` calls the completion function again, and it narrows the results down, so the hard limit is not a problem. That doesn't happen with `ido-completing-read`.

> I think 2) could be a nice feature, but I'm not sure using it for autocompletion would work well.

I don't mean autocompletion here. What I mean is: press `M-x ruby-dev-show-doc RET`, type `gsub`, press Tab -> no matches. That can be handled better.

Thanks for the pointer to `find-method`. I was thinking of adding an `apropos`-like command, and this might be an easy solution.

> Well, good luck with your project ;)

Thanks!
