### ISSUE TITLE
Correct evaluation is alternating

### ISSUE THREAD

**Issue by nodo** [Mon-Ouie/ruby-dev.el#4]
I have correctly installed pry, yard and ruby-dev.el.

I got some unexpected behaviours, here is my report:
1. I open the file `try.rb` and I type `C-c C-s` then I try to do a simple addition `3+2` and I can see the correct result. I do the very same steps again, but instead of the result I get `nil`. The correct behaviour is alternating. I can't figure out what's the problem.
2. I report the same issue evaluating a ruby-sexp expression. It alternates the correct result with `nil`.

Hope it helps,
I'd love to contribute to your project

Cheers

PS
`ruby 2.0.0dev (2013-02-08 trunk 39161) [x86_64-darwin12.3.0]`
`Pry version 0.9.12.2 on Ruby 2.0.0`
`yard 0.8.6.2`

**Comment by Mon-Ouie** [comment]
Hey,

Could you check the value for `ruby-dev-response-queue` before performing both evaluations? I'm assuming for some reason an unwanted response is being introduced in the queue.

Thanks for reporting the issue!

**Comment by nodo** [comment]
Thanks for your reply,

I opened a file a started a new REPL with PRY.
The value of `ruby-dev-response-queue` is:

```
(((argument) (id . "main") (type . "repl-handle")))
```

Then I tried to evaluate (1 + 1) and the returned result is `nil`, while the status of the queue is:

```
(((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)))
```

I tried again to evaluate the same expression, the returned value is again `nil`, while the queue is:

```
(((result . "2") (success . t)) ((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)))
```

Finally I tried again and it gives the correct result, the queue status is:

```
(((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)) ((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)))
```

I tried again and the result is `nil`:

```
(((result . "2") (success . t)) ((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)) ((line . 1) (filename . "/tmp/try.rb") (code . "(1 + 1)") (type . "eval")) ((result . "2") (success . t)))
```

Do you need other information? What do you think about this behaviour?

Cheers

**Comment by Mon-Ouie** [comment]
This is quite odd. What's happening is, when the client (run from Emacs) sends a message to the server (the Ruby script), the server is printing it in its output, instead of only printing the response, so when the client looks at the next response it received, instead of checking the real response, it is reading the message it just sent to the server.

So it looks like printf-debugging that wasn't properly removed, but I can't reproduce the issue and can't seem to find a place where I'd print the object sent by the client. Can you check if your `ruby-dev.rb' is the same as the one on the repo?

**Comment by nodo** [comment]
The file is updated.

BTW this is my emacs version:

```
GNU Emacs 24.3.50.1
```

I do not have time to check it at the moment but could ruby 2.0 cause problems?

**Comment by Mon-Ouie** [comment]
I'm using ruby 2.0 as well and can't reproduce your issue, so no (although I'm using ruby 2.0.0p247, but it would still surprise me if the ruby version was the cause of this).

**Comment by nodo** [comment]
I am going to debug the issue on my own and I'll let you know!
I'll probably need your help in some cases :)

**Comment by nodo** [comment]
After long time, I have tried again using `ruby 2.2.2`, `emacs 25.1.1`, `pry 0.10.4`. Works like a charm! 👍
