### ISSUE TITLE
Pry REPL does not work, terminal is not fully functional

### ISSUE THREAD

**Issue by nodo** [Mon-Ouie/ruby-dev.el#5]
When I open the REPL buffer and I type a command it shows the following message:

`ruby-dev failed to parse line: WARNING: terminal is not fully functional^M`

I do not know if it is a bug or it is my problem (I use Mac OSX, so I do not think it is a matter of carriage return...).

The details of my system are the following:
`ruby 2.0.0dev (2013-02-08 trunk 39161) [x86_64-darwin12.3.0]`
`Pry version 0.9.12.2 on Ruby 2.0.0`
`yard 0.8.6.2`

Cheers

**Comment by proofit404** [comment]
This is not a error at all. It's just a `comint-mode` warning for program which try to handle terminal.
All that you need simple disable pry's pager functionality. See [Pry wiki](https://github.com/pry/pry/wiki/Customization-and-configuration#pager) for more info.

**Comment by nodo** [comment]
Right! The REPL now is perfectly fine.

Thanks @proofit404 :+1:

**Comment by proofit404** [comment]
You're welcome!

**Comment by proofit404** [comment]
@Mon-Ouie maybe there is some reason add this setting into `ruby-dev.rb` file?
