### ISSUE TITLE
REPL doesn't start, throws an error

### ISSUE THREAD

**Issue by ghost** [Mon-Ouie/ruby-dev.el#7]
Throws `error in process filter: Unrecognized keyword: "from" [2 times]`

OSX 10.8.4
GNU Emacs 24.3.1 (x86_64-apple-darwin12.3.0, NS apple-appkit-1187.37)
Both pry and yard are installed. What can I do?

Thanks in advance.

May or may not be the same problem as #1 but ruby-dev.rb runs just fine in iTerm

**Comment by Mon-Ouie** [comment]
Hey,

If the script does work when run from your terminal but not when run by `ruby-dev.el', then there must be a difference in your environment. Could you use`toggle-debug-on-error' and also look at the value of `ruby-dev-received-output'?

**Comment by ghost** [comment]
Thanks for your suggestions! 

I enabled debug on error and it outputs this among other things:
 ``ruby-dev-enqueue-response("  from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:211:in `activate'\n")
  ruby-dev-process-filter(#<process ruby-dev> "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:777:in `report_activate_error': Could not find RubyGem pry (~> 0.9) (Gem::LoadError)\n   from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:211:in `activate'\n    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1056:in `gem'\n    from /Users/eugene/.emacs.d/elpa/ruby-dev-20130811.1051/ruby-dev.rb:5\n")
  accept-process-output(#<process ruby-dev>)`

Looks like it talks to the system ruby, seems to be a problem with my $PATH.
Double-checked and when I run emacs in a terminal, REPL works just fine. Sorry to bother you, thanks for your time.
